services:
  proapp-eureka-server:
    image: proapp-eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - ms-network
  oracle:
    image: oracle/database:21.3.0-se2
    container_name: oracledb
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=orcl
      - ORACLE_PWD=12345
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - ms-network
volumes:
  redis_data:
  oracle_data:
networks:
  ms-network:
    driver: bridge


